openapi: 3.0.1
info:
  title: Aggregate Plugin
  description: A plugin that allows the user to price simple reinsurance portfolios using chatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /price:
    post:
      summary: "Start aggregation"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                percentile:
                  type: number
                  default: 0.99
      responses:
        '200':
          description: "Aggregation result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
